setting:
  data: amazon_baby # Dataset
  gpu_id: 1 # GPU_ID
  baseline: BPRMF # Base model
  wrapper: FLEXMORE # Multi-Objective Method
  epochs: 500 # Number of epochs
  validation_rate: 10 # Period of evaluation during training
  validation_metric: ndcg@20 # Metric of evaluation during training
  batch_size: 2048 # Batch size
hyperparameters:
  dim: [64] # Dimension for embedding
  lr: [0.005, 0.001, 0.0005] # Learning rate
  l_2: [0.01, 0.005, 0.001] #L2 penalty
  mode: [rpm] # Which loss to use
  g_n: [loss+] # Modality of gradient normalization
  atk: [20] # Cutoff when computing approximated metrics
  ranker: [AIMLE]



